# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
inhibit_all_warnings!

target 'FCAnimations' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

    pod 'AFNetworking'
    pod 'SDWebImage'
    pod 'Masonry'
    pod 'MJRefresh'
    pod 'YYCategories'
#    pod 'FMDB'
#    pod 'MBProgressHUD'
#   pod 'DZNEmptyDataSet'
#    pod 'IQKeyboardManager'

  # Pods for FCAnimations

end
